EasyPost/Shipment.cs, EasyPostTest/ShipmentTest.cs
Addded unit test to test new property
=> Added property for specifying carrier accounts

EasyPost/Options.cs
https://github.com/EasyPost/easypost-csharp/issues/64
=> Added carrier_notification_email

EasyPost/Options.cs
- commercial_invoice_signature
- parties_to_transaction_are_related
// cc @jingta
=> Add new `Options` fields:

EasyPost/Options.cs
=> Added `options.importer_address_id`

EasyPost/Options.cs
Fixes EasyPost/easypost-csharp#142
=> Add `commercial_invoice_letterhead` option

EasyPost.NetCore20/EasyPost.NetCore20.csproj, EasyPost/EasyPost.csproj, EasyPost/packages.config, EasyPostTest/EasyPostTest.csproj, EasyPostTest/packages.config
Upgrade RestSharp to version 106.12.0.
Closes #147
=> Upgrade RestSharp to 106.12.0

CHANGELOG.md, EasyPost.Tests/ClientConfigurationTest.cs, EasyPost/Address.cs, EasyPost/ApiKey.cs, EasyPost/Batch.cs, EasyPost/CarrierAccount.cs, EasyPost/CarrierType.cs, EasyPost/ClientConfiguration.cs, EasyPost/CustomsInfo.cs, EasyPost/CustomsItem.cs, EasyPost/Event.cs, EasyPost/Order.cs, EasyPost/Parcel.cs, EasyPost/Pickup.cs, EasyPost/Rate.cs, EasyPost/Report.cs, EasyPost/ScanForm.cs, EasyPost/Shipment.cs, EasyPost/Tracker.cs, EasyPost/User.cs, EasyPost/Webhook.cs
Add '**v2**' to the DeefaultBaseUrl and remove '**v2**' in every request URL string.
=> Add v2 to the DefaultBaseUrl and remove v2 in every request url string.

CHANGELOG.md, EasyPost.Tests/TimeoutTest.cs, EasyPost/Client.cs
Add a 30-second default connection timeout to all requests
Add a 60-second default request timeout to all requests
Add setter and getter to allow the user to change the connection and request timeout
=> Timeout for http

CHANGELOG.md, EasyPost.Tests/TrackerTest.cs, EasyPost/Tracker.cs
Add functionality to create trackers in bulk for our C# library.
Currently, our C# library is missing one of the core features.
Add CreateList method in Tracker class.
Add a unit test in TrackerTest.cs and pass the result.
=> add createList in tracker class.

EasyPost.Net35/EasyPost.Net35.csproj, EasyPost.Net40/EasyPost.Net40.csproj, EasyPost.NetCore20/EasyPost.NetCore20.csproj, EasyPost.NetCore31/EasyPost.NetCore31.csproj, EasyPost.Tests/UserTest.cs, EasyPost/Brand.cs, EasyPost/EasyPost.csproj, EasyPost/User.cs
Finally, the C# library supports the ability to get update your brand with `user.UpdateBrand()`
- The new `user.UpdateBrand()` function to update the associated user's brand. Pass in a `Dictionary<string, object>` as parameter. Function returns a `Brand` object.
- Docstring for this function.
- Added new `Brand` class, which features all necessary properties.
- A new `UserTest.TestUpdateBrand()` test for this feature
Classes, functions and tests have been imported/linked to all projects/versions, and all tests pass.
=> Add support for updating user's brand

CHANGELOG.md, EasyPost.nuspec, EasyPost/VersionInfo.cs, README.md
=> chore: prepare v2.8.0 for release

CHANGELOG.md, EasyPost.Net/Options.cs, EasyPost.NetFramework/Options.cs
* Adds missing `billing_ref` and `dropoff_type` options
=> feat: adds missing dropoff_type and billing_ref options

EasyPost.Net/ApiKey.cs, EasyPost.Tests.Net/RefundTest.cs
Just some light cleanup on things I noticed
- Remove a bad docstring in ApiKey.cs
- Switch refund tests VCR to Replay
=> [Chore] Minor cleanup

.github/workflows/ci.yml
This PR bumps `actions/checkout@v2` to `actions/checkout@v3`
=> update github action to v3

EasyPost/Shipment.cs
This is a catch-all for very minor fixes to include in the next release of the C# library.
By "very minor", I mean, e.g.:
- Docstring changes
- Changelog changes
- Spelling changes
- Variable name changes
No functionality changes, either internal or external, should be included in this branch/pull request.
What doesn't belong here:
- New functions, regardless of access/visibilty level
- Changes to existing functions' signatures (no changes to return types, parameters, function names, etc.)
- Changes to internal logic inside of functions
- "Improvements" or "refinements" to existing functionality
=> WIP: Minor fixes and patches

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs, README.md, UPGRADE_GUIDE.md
Prepares v3.0.0 for release.
NA
=> chore: prepares v3.0.0 for release

README.md
Adds a missing import required to copy/paste the working example to the README
Tested locally
=> fix: add missing README example import

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v3.1.0 for release

EasyPost/Smartrate.cs
add missing `billing_type` attribute to smart rate
=> add billing_type in smart rate.

EasyPost/EasyPost.csproj, EasyPost/Resource.cs, EasyPost/Utilities/Enumeration.cs, EasyPost/Utilities/JsonSerialization.cs, EasyPost/Utilities/Rates.cs
- Suppress nullability warnings
- Suppress obsolete function warnings
All unit tests run as expected
Remaining errors:
=> Clean up build warnings

CHANGELOG.md, EasyPost.nuspec, EasyPost/VersionInfo.cs
=> chore: prepare v2.8.3

CHANGELOG.md, EasyPost.nuspec
- Skip .NET Framework 4.X builds
- Update CHANGELOG.md
=> Fix build issues on backport

EasyPost/PaymentMethod.cs
- Fix type of credit card expiration details
- All tests pass as expected
=> Fix type of credit card expiration details

EasyPost/Utilities/RuntimeInfo.cs
Compiler switch needs to check for .NET Standard, not .NET Framework
- All tests pass
=> Fix .NET Framework targeting for constructing user agent

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v3.2.0 for release

scripts/build_project.bat, scripts/delete_old_assemblies.bat, scripts/install_cert.bat, scripts/lint_scripts.bat, scripts/pack_nuget.bat, scripts/sign_dlls.bat, scripts/sign_nuget.bat
- Fix batch scripts throwing errors
- We did it live
=> Fix batch script exits

CHANGELOG.md
Fixes a typo with the GenerateForm function name in the CHANGELOG.
=> fix: CHANGELOG name for GenerateForm

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v3.4.0 for release

.github/workflows/ci.yml, Makefile, README.md
Unified the Makefile like we have in other libs, adds a release target.
=> chore: unifies Makefile and adds release target

.github/workflows/ci.yml, .gitignore, EasyPost.Tests/EasyPost.Tests.csproj, EasyPost.Tests/TestUtils.cs, Makefile
- Fix security scan issue by locking to a compatible version of the utility
- Fix .NET Standard unit. 
- Bump EasyVCR to 0.4.0
- All unit tests pass locally
- All CI tests pass remotely
=> Fix CI errors

EasyPost/Options.cs
- Add duty_payment option
Closes #315 
- No changes to unit tests
=> Add duty_payment option

EasyPost.Tests/EndShipperTest.cs, EasyPost.Tests/cassettes/net/end_shipper/all.json, EasyPost.Tests/cassettes/net/end_shipper/create.json, EasyPost.Tests/cassettes/net/end_shipper/retrieve.json, EasyPost.Tests/cassettes/net/end_shipper/update.json, EasyPost.Tests/cassettes/netstandard/end_shipper/all.json, EasyPost.Tests/cassettes/netstandard/end_shipper/create.json, EasyPost.Tests/cassettes/netstandard/end_shipper/retrieve.json, EasyPost.Tests/cassettes/netstandard/end_shipper/update.json, EasyPost/EndShipper.cs, EasyPost/EndShipperCollection.cs, EasyPost/Utilities/Attributes/DeprecationDetails.cs
- Copy EndShipper class to main namespace
- Mark EndShipper beta as obsolete
- Introduce new custom attribute to note deprecation details
- New EndShipperCollection class to wrap list of EndShipper objects (like Addresses)
- EndShipper.All returns EndShipperCollection object
- Unit tests updated
- Unit tests updated and passing
=> Move EndShipper to general availability

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepares v3.5.0 for release

.github/workflows/ci.yml, EasyPost.Tests.FSharp/EasyPost.Tests.FSharp.fsproj, EasyPost.Tests.FSharp/packages.lock.json, EasyPost.Tests.VB/EasyPost.Tests.VB.vbproj, EasyPost.Tests.VB/packages.lock.json, EasyPost.Tests/EasyPost.Tests.csproj, EasyPost.Tests/packages.lock.json, EasyPost/EasyPost.csproj, EasyPost/packages.lock.json, README.md
- CI process now caches any downloaded NuGet packages to speed up builds
=> Configure GitHub Actions to cache NuGet packages

CHANGELOG.md, EasyPost/Options.cs
Adds `end_shipper_id` shipment option
=> feat: adds end_shipper_id shipment option

EasyPost.nuspec, README.md
- Update README details to account for re-architecture
- N/A
=> Update README for rewrite

EasyPost.Tests.FSharp/packages.lock.json, EasyPost.Tests/Fixture.cs, EasyPost.Tests/ReferralTest.cs, EasyPost.Tests/TestUtils.cs, EasyPost.Tests/cassettes/net/referral/all.json, EasyPost.Tests/cassettes/net/referral/create.json, EasyPost.Tests/cassettes/net/referral/update.json, EasyPost.Tests/cassettes/netstandard/referral/all.json, EasyPost.Tests/cassettes/netstandard/referral/create.json, EasyPost.Tests/cassettes/netstandard/referral/update.json, EasyPost/BaseUser.cs, EasyPost/Billing.cs, EasyPost/PaymentMethod.cs, EasyPost/ReferralCustomer.cs, EasyPost/ReferralCustomerCollection.cs, EasyPost/Request.cs, EasyPost/User.cs
- Add support for Partner/White Label:
- Create a new referral user
- Update a referral user's email address
- List all referral users
- Add a credit card to a referral user's account
- Add unit tests for Partner/White Label
- New unit tests added and recorded
- Unit test for adding credit card disabled due to VCR issues
- Can confirm test works E2E
=> feat: Add support for Partner/White Label

CHANGELOG.md
=> Add White Label features to CHANGELOG

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepares v3.6.0 for release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Options.cs, EasyPost/Properties/VersionInfo.cs
=> chore: prepares v3.6.1 for release

.github/workflows/ci.yml, Makefile
Copy of https://github.com/EasyPost/easypost-csharp/pull/338 for v4
- N/A
=> Use dotnet-format rather than broken dotnet format

.github/workflows/ci.yml, Makefile
- Swap linting utility for one that isn't broken 🙄 
- N/A
=> Use dotnet-format instead of broken dotnet format

UPGRADE_GUIDE.md
- Add upgrade guide for v3->v4
- N/A
=> v4 Upgrade Guide

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs, README.md
Prepares v4.0.0-rc1 for release
=> v4.0.0 rc1

EasyPost/Properties/VersionInfo.cs
AssemblyVersion must be numerical only, fixing that for release candidate.
=> fix assembly version

CHANGELOG.md, UPGRADE_GUIDE.md
- Note changes to namespaces in v4 changes
- N/A
=> Call out namespace changes in CHANGELOG.md and UPGRADE_GUIDE.md

CHANGELOG.md, EasyPost.Tests/ErrorTest.cs, EasyPost/Exceptions/API/_Base.cs
- Parse and concatenate error message if it's accidentally an array
- New unit test to confirm parsing of multiple error message elements works correctly
=> Improve API error parsing

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v4.0.0 for release

CHANGELOG.md
=> chore: clarify CHANGELOG for v4

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepares v4.0.1 for release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
- Update Changelog
- Bump version from 4.0.1 to 4.0.2
- N/A
=> Prep for 4.0.2 release

README.md
Adds Fuget link for library docs. Because these get handled automatically for us and are versioned into the past, we shouldn't need to build these ourselves locally.
=> chore: add fuget link

.github/workflows/ci.yml, EasyPost.Tests/packages.lock.json, Makefile, README.md, generate_test_reports.sh
- Generate coverage report when pushing to master
- Upload coverage report to coveralls.io
- Temporarily enabled for all pushes (not just master merges), report uploaded correctly: https://coveralls.io/github/EasyPost/easypost-csharp
=> Upload coverage report to coveralls.io

EasyPost.Tests/CalculationTests/RatesTests.cs, EasyPost.Tests/EasyPost.Tests.csproj, EasyPost.Tests/ModelsTests/TrackerTest.cs, EasyPost.Tests/TestUtils.cs, EasyPost/Calculation/Rates.cs, EasyPost/Services/PartnerService.cs, EasyPost/Utilities/Enumeration.cs
- Fixes coverage warnings raised by the coverage tool (noted here: https://github.com/EasyPost/easypost-csharp/pull/370/files)
- N/A
=> Fix coverage warnings

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v4.1.0 for release

CHANGELOG.md, EasyPost.Tests/Fixture.cs, EasyPost.Tests/ServicesTests/Beta/ReferralServiceTest.cs, EasyPost.Tests/ServicesTests/BillingServiceTest.cs, EasyPost.Tests/ServicesTests/PartnerServiceTest.cs, EasyPost.Tests/ServicesTests/RateServiceTest.cs, EasyPost.Tests/TestUtils.cs, EasyPost.Tests/cassettes/net/beta_referral_service/add_payment_method.json, EasyPost.Tests/cassettes/net/beta_referral_service/refund_by_amount.json, EasyPost.Tests/cassettes/net/beta_referral_service/refund_by_payment_log.json, EasyPost.Tests/cassettes/netstandard/beta_referral_service/add_payment_method.json, EasyPost.Tests/cassettes/netstandard/beta_referral_service/refund_by_amount.json, EasyPost.Tests/cassettes/netstandard/beta_referral_service/refund_by_payment_log.json, EasyPost/BetaClient.cs, EasyPost/Models/API/Beta/PaymentRefund.cs, EasyPost/Models/API/Shipment.cs, EasyPost/Services/Beta/ReferralService.cs, EasyPost/Services/PartnerService.cs, EasyPost/_base/EasyPostClient.cs, EasyPost/_base/WithClient.cs, README.md
- Add beta "add payment method" and "refund" functions for referral customers
- Add `Referral` service to beta client
- Add unit tests, cassettes
- Change "Referral User" to "Referral Customer" app-wide
- Change "url" to "endpoint" to better explain parameter for internal requests.
- This is never exposed to users, and does not constitute a breaking change. Just housekeeping.
- New unit tests, cassettes
=> feat: add payment method and refund functions

CHANGELOG.md, EasyPost.nuspec, EasyPost/Models/API/Options.cs, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v4.2.0 for release

CHANGELOG.md, EasyPost.Tests/ServicesTests/PickupServiceTest.cs, EasyPost.Tests/cassettes/net/pickup_service/all.json, EasyPost.Tests/cassettes/netstandard/pickup_service/all.json, EasyPost/Models/API/Pickup.cs, EasyPost/Services/PickupService.cs
- New function to retrieve all pickups
- New unit test, cassettes
=> feat: New function to retrieve all pickups

CHANGELOG.md, EasyPost.Tests/ServicesTests/EventServiceTest.cs, EasyPost.Tests/cassettes/net/event_service/retrieve_payload_for_event.json, EasyPost.Tests/cassettes/net/event_service/retrieve_payloads_for_event.json, EasyPost.Tests/cassettes/netstandard/event_service/retrieve_payload_for_event.json, EasyPost.Tests/cassettes/netstandard/event_service/retrieve_payloads_for_event.json, EasyPost/Models/API/Event.cs, EasyPost/Models/API/Payload.cs, EasyPost/Services/EventService.cs
- Add function to retrieve payload/payloads for a given Event
- Add unit tests, cassettes
- Add new Payload class, fix Event class schema
- New unit tests, cassettes
=> feat: Add functions to retrieve event payload(s)

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v4.3.0 for release

README.md
=> fix: lib docs wording

EasyPost.Tests.FSharp/packages.lock.json, EasyPost.Tests/ServicesTests/PartnerServiceTest.cs, EasyPost.Tests/TestUtils.cs, EasyPost.Tests/UtilitiesTests/EnumTest.cs, EasyPost.Tests/_Utilities/Annotations/TestType.cs, EasyPost/BetaClient.cs
- Address some style suggestions from Rosalyn
- N/A, no effect on end-user functionality
=> [chore] Seal internal/private classes to appease Rosalyn

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v4.4.0 for release

CHANGELOG.md, EasyPost/Models/API/Insurance.cs
add missing fee attribute to insurance
=> add missing fee attribute to insurance

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v4.5.0 for release

EasyPost/Constants.cs, EasyPost/Exceptions/General/EndOfPaginationError.cs
Allow users to access error message template for EndOfPaginationError for whatever they might need
- N/A
=> Add EndOfPaginationError message to Constants

Makefile, scripts/unix/install_osslsigncode.sh
- new script, makefile step to install tools needed for releasing on Mac
- Works
=> [chore] Tools to help Mac release process

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v4.6.0 for release

CHANGELOG.md, EasyPost/Models/API/Payload.cs
fix the type of RequestBody in payload class
=> fix the type of RequestBody in payload class

CHANGELOG.md, EasyPost.Tests/Fixture.cs, EasyPost/BetaFeatures/Parameters/CustomsInfo/Create.cs
- Add missing parameter to Customs Info creation parameter set
- N/A
=> Add Declaration parameter to customs info

CHANGELOG.md, EasyPost.nuspec
Follow up work to https://github.com/EasyPost/easypost-csharp/pull/439
- N/A
=> [chore] Update RestSharp dependency ranges in nuspec

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v4.6.1 for release

EasyPost.Tests/CalculationTests/RatesTests.cs, EasyPost.Tests/ModelsTests/SmartrateAccuracyTests.cs, EasyPost.Tests/ModelsTests/TimeInTransitTests.cs, EasyPost.Tests/ServicesTests/ShipmentServiceTest.cs, EasyPost.Tests/UtilitiesTests/SwitchCaseTest.cs, EasyPost/Calculation/Rates.cs, EasyPost/Models/API/Beta/CarrierMetadata.cs, EasyPost/Models/API/Smartrate.cs, EasyPost/Models/API/SmartrateAccuracy.cs, EasyPost/Models/API/TimeInTransit.cs, EasyPost/Services/ShipmentService.cs, EasyPost/Utilities/Rates.cs
- Rename all instances of smartrate to SmartRate/Smart Rate
- Remove obsolete smart rate filtering function on shipment service
- Unit tests updated according, no new recordings needed
=> [chore] Fix casing for SmartRate

Makefile, docfx.json
Move the docs config file to the root of the project
=> fix: docs generation

EasyPost.Tests/BetaFeaturesTests/ServicesTests/ShipmentServiceTest.cs, EasyPost.Tests/Fixture.cs, EasyPost.Tests/ServicesTests/ShipmentServiceTest.cs, EasyPost.Tests/cassettes/net/shipment_service/estimated_delivery_dates.json, EasyPost.Tests/cassettes/net/shipment_service_with_parameters/estimated_delivery_dates.json, EasyPost.Tests/cassettes/netstandard/shipment_service/estimated_delivery_dates.json, EasyPost.Tests/cassettes/netstandard/shipment_service_with_parameters/estimated_delivery_dates.json, EasyPost/BetaFeatures/Parameters/Shipments/GetEstimatedDeliveryDate.cs, EasyPost/BetaFeatures/Parameters/Shipments/RetrieveEstimatedDeliveryDate.cs, EasyPost/Models/API/RateWithEstimatedDeliveryDate.cs, EasyPost/Models/API/TimeInTransit.cs, EasyPost/Services/ShipmentService.cs
- Add `RetrieveEstimatedDeliveryDate` function to Shipment service
- Non-breaking tweak to base class for `TimeInTransit` model (ephemeral)
- Add unit tests (legacy + Parameters methods)
- Add cassettes, fixtures as needed
=> Delivery date

EasyPost.Tests/ServicesTests/AddressServiceTest.cs, EasyPost.Tests/ServicesTests/EventServiceTest.cs, EasyPost.Tests/ServicesTests/InsuranceServiceTest.cs, EasyPost.Tests/ServicesTests/PickupServiceTest.cs, EasyPost.Tests/ServicesTests/ReferralCustomerServiceTest.cs, EasyPost.Tests/ServicesTests/RefundServiceTest.cs, EasyPost.Tests/ServicesTests/ReportServiceTest.cs, EasyPost.Tests/ServicesTests/ScanFormServiceTest.cs, EasyPost.Tests/ServicesTests/ShipmentServiceTest.cs, EasyPost.Tests/ServicesTests/TrackerServiceTest.cs, EasyPost.Tests/_Utilities/Assertions/CollectionAsserts.cs
- Stop GitHub code analysis complaining about unused captured exceptions
- N/A
=> [chore] Address GitHub code analysis

EasyPost.Tests.FSharp/EasyPost.Tests.FSharp.fsproj, EasyPost.Tests.FSharp/FSharpCompileTest.fs, EasyPost.Tests.FSharp/packages.lock.json, EasyPost.Tests.VB/EasyPost.Tests.VB.vbproj, EasyPost.Tests.VB/VbCompileTest.vb, EasyPost.Tests.VB/packages.lock.json
- Target NET 7.0 for VB and F# compile tests
- N/A
=> [chore] Bump VB, F# tests to NET 7.0

EasyPost.Tests/ClientTest.cs, EasyPost.Tests/Fixture.cs, EasyPost.Tests/HttpTests/ClientConfigurationTest.cs, EasyPost.Tests/ServicesTests/Beta/RateServiceTest.cs, EasyPost.Tests/ServicesTests/RateServiceTest.cs, EasyPost.Tests/ServicesTests/WithParameters/ReferralCustomerServiceTest.cs, EasyPost.Tests/ServicesTests/WithParameters/ShipmentServiceTest.cs, EasyPost.Tests/ServicesTests/WithParameters/WebhookServiceTest.cs, EasyPost.Tests/UtilitiesTests/EnumerablesTest.cs, EasyPost.Tests/_Utilities/Assertions/CollectionAsserts.cs, EasyPost.Tests/_Utilities/UnitTest.cs, EasyPost/ClientConfiguration.cs, EasyPost/Parameters/BaseParameters.cs
- Address various warnings in IDE
- Remove unused imports, test utilities
- All tests pass
=> [chore] Address IDE warnings

CHANGELOG.md, UPGRADE_GUIDE.md
=> [chore] `v5` Upgrade Guide and Changelog

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs, README.md
- Bump version number
- Update README
- N/A
=> [chore] Prep for v5.0.0 release

EasyPost.nuspec
=> [chore] Remove RestSharp dependency from NuGet spec

CHANGELOG.md, EasyPost.Tests.FSharp/packages.lock.json, EasyPost.Tests.VB/packages.lock.json, EasyPost.Tests/packages.lock.json, EasyPost.nuspec, EasyPost/EasyPost.csproj, EasyPost/packages.lock.json
- Library only works with RestSharp v108 due to breaking changes in newer versions of RestSharp (#435)
=> [chore] Rollback RestSharp range extension

EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> [chore] Prep v4.6.2. release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v5.1.0 for release

Makefile, README.md
=> fix: make lint target

EasyPost/Models/API/Options.cs
=> [chore] Add tax_id_expiration_date to options

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> [chore] Prep version, changelog for v5.1.1 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
Next version is going to be v5.2.0, not v5.1.1 due to new feature (hooks)
=> [chore] Prep for v5.2.0 release

CHANGELOG.md, EasyPost.Tests/ExceptionsTests/ExceptionsTest.cs, EasyPost/Constants.cs, EasyPost/Exceptions/API/BadRequestError.cs
- Maps 400 status codes to new `BadRequestError` class
=> feat: maps 400 status codes to BadRequestError class

.gitattributes, EasyPost.Integration/EasyPost.Integration.csproj, EasyPost.Integration/Synchronous.cs, EasyPost.Integration/TestUtils.cs, EasyPost.Integration/Utilities/Attributes/TestType.cs, EasyPost.Integration/cassettes/net/synchronous/async.json, EasyPost.Integration/cassettes/net/synchronous/via_get_awaiter.json, EasyPost.Integration/cassettes/net/synchronous/via_result.json, EasyPost.Integration/cassettes/net/synchronous_mvc_controller/async.json, EasyPost.Integration/cassettes/net/synchronous_mvc_controller/via_task_factory.json, EasyPost.Integration/cassettes/netstandard/synchronous/async.json, EasyPost.Integration/cassettes/netstandard/synchronous/via_get_awaiter.json, EasyPost.Integration/cassettes/netstandard/synchronous/via_result.json, EasyPost.Integration/cassettes/netstandard/synchronous_mvc_controller/async.json, EasyPost.Integration/cassettes/netstandard/synchronous_mvc_controller/via_task_factory.json
- Add integration tests verifying that asynchronous functions can be run synchronously via multiple methods (re: #499)
- Add VCR, associated utilities for integration test suite
- New integration tests, cassettes for async/sync tests
=> [chore] Add integration test for sync/async support

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> [chore] Prep for v5.4.0 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> [chore] Prep version number, CHANGELOG for v5.4.1 release

scripts/unix/build_release_nuget.sh, scripts/unix/sign_nuget.sh
Release script was previously looking in the wrong place for a finished NuGet package (this does NOT invalidate our previous NuGet packages)
=> [chore] Clarify, fix release script paths for NuGet files

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
- Update CHANGELOG
- Bump version numbers
- N/A
=> [chore] Prep for 5.5.0 release

README.md, scripts/unix/setup.sh
- Add Apple Silicon check in dotnet installation script, redirect to brew
- Add details about using `make unit-test fw=` to avoid .NET Framework issues on Apple Silicon
- Install script checks for Apple Silicon correctly
=> [chore] Account for Apple Silicon in development

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> chore: prepare v5.8.0 for release

EasyPost/Hooks.cs, EasyPost/Models/API/CarrierAccountType.cs, EasyPost/Parameters/BaseParameters.cs, EasyPost/Parameters/IBaseParameters.cs, README.md
- Add missing docstrings for Hooks
- No changes to functionality or compatibility, all unit tests pass as expected
=> [chore] Add missing docstrings

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs, UPGRADE_GUIDE.md
Prep changelog, upgrade guide, version numbers for new release
- N/A
=> [chore] Prep for v6.0.0 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> [chore] Change version to 6.0.0 RC1

.github/workflows/release.yml, EasyPost.nuspec
=> [fix] Drop NET Core 3.1, add .NET 8.0 for NuGet

EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> [chore] Bump version to v6.0.0 RC 2

EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs, Makefile
=> [fix] Fix NuGet release make step, bump to v6.0.0 RC 3

.github/workflows/release.yml, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs, Makefile
=> [chore] Improve release process

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> [chore] Prep v6.0.0 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
- Bump version number
- Update changelog
=> [chore] Prep for v6.1.0 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
Update version number, changelog
- N/A
=> [chore] Prep for v6.2.0 release

EasyPost/Models/API/Options.cs
Add description for `carrier_notification_email` and `carrier_notification_sms`
N/A
=> [chore] Add description for option attributes

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> [chore] Prep for v6.2.1 release

CHANGELOG.md, EasyPost.Tests/ServicesTests/BillingServiceTest.cs, EasyPost.nuspec, EasyPost/Models/API/PaymentMethod.cs, EasyPost/Properties/VersionInfo.cs
=> prep release v6.3.0

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
- Bump version number, update CHANGELOG
=> [chore] Prep for v6.3.1 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
Bump version number, update changelog
=> [chore] Prep for v6.4.0 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
Bump version number, update changelog
=> [chore] Prep v6.5.0 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> [chore] Prep for v6.6.0 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Models/API/Claim.cs, EasyPost/Properties/VersionInfo.cs, EasyPost/Services/ClaimService.cs
- Bump version number
- Update CHANGELOG
- Remove bad docstring links
=> [chore] Prep for v6.7.0 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> [chore] Prep for v6.7.1 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
=> [chore] Prep for v6.7.2 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
Bump version number, update changelog
=> [chore] Prep for v6.7.3 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
- Update version number
- Update changelog
=> [chore] Prep for v6.8.1 release

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs
Update changelog, bump version number to 6.9.0
=> [chore] Prep for v6.9.0 release

CHANGELOG.md, EasyPost.Tests/Fixture.cs, EasyPost.Tests/FixtureData.cs, EasyPost.Tests/ServicesTests/Beta/ReferralServiceTest.cs, EasyPost.Tests/ServicesTests/ReferralCustomerServiceTest.cs, EasyPost.Tests/ServicesTests/ReportServiceTest.cs, EasyPost.Tests/ServicesTests/WithParameters/ReportServiceTest.cs, EasyPost.Tests/cassettes/net/beta_referral_service/create_bank_account_client_secret.json, EasyPost.Tests/cassettes/net/beta_referral_service/create_credit_card_client_secret.json, EasyPost.Tests/cassettes/net/referral_customer_service/add_bank_account_from_stripe.json, EasyPost.Tests/cassettes/net/referral_customer_service/add_credit_card_from_stripe.json, EasyPost/Models/API/PaymentMethod.cs, EasyPost/Models/API/StripeClientSecret.cs, EasyPost/Services/Beta/ReferralCustomerService.cs, EasyPost/Services/ReferralCustomerService.cs, Makefile, scripts/unix/setup.sh
- Adds the following functions to assist ReferralCustomer in adding credit cards and bank accounts:
- `Beta.ReferralCustomer.CreateCreditCardClientSecret`
- `Beta.ReferralCustomer.CreateBankAccountClientSecret`
- `ReferralCustomer.AddCreditCardFromStripe`
- `ReferralCustomer.AddBankAccountFromStripe`
- Adds tests for new functions
=> feat: new billing functions for referral customer

CHANGELOG.md, EasyPost.Integration/Basics.cs, EasyPost.Tests/ServicesTests/CarrierAccountServiceTest.cs, EasyPost.Tests/cassettes/net/carrier_account_service/create_with_oauth.json, EasyPost/Constants.cs, EasyPost/Models/API/CarrierAccountType.cs, EasyPost/Parameters/CarrierAccount/CreateOauth.cs, EasyPost/Services/CarrierAccountService.cs
=> feat: route Amazon account to correct endpoint

CHANGELOG.md, EasyPost/Models/API/Tracker.cs, EasyPost/Models/API/TrackingDetail.cs
=> feat: adds missing tracker props

CHANGELOG.md, EasyPost.nuspec, EasyPost/Properties/VersionInfo.cs, UPGRADE_GUIDE.md
=> chore: prep v7.0.0 for release

.github/workflows/manual_release_prep.yml, .github/workflows/release.yml
=> fix: install all needed SDKs for releasing
