EasyPost/easypost-csharp

- EasyPost.Net40/EasyPost.Net40.csproj
- EasyPost/Client.cs
- EasyPost/ClientConfiguration.cs
- EasyPost/ClientFactory.cs
- EasyPost/EasyPost.csproj
- EasyPost/Request.cs
- EasyPostTest/ClientConfigurationTest.cs
- EasyPostTest/ClientFactoryTest.cs
- EasyPostTest/ClientTest.cs
- EasyPostTest/EasyPostTest.csproj
- README.md
Trying this again.. continuation of a botched PR #35 ..
Here is the complete set of changes to help the EasyPost lib support multiple API keys per application.
As discussed, the current limitation of the static fields EasyPost.Client.apiKey creates contention across multiple calls to EasyPost.Client (as in web requests/threads/series of method calls), which can be seen by running the ClientTest fixture in its entirety prior to commit 5198aef
By refactoring the ApiKey + ApiBaseUrl to a separate ClientConfiguration class and by providing the appropriate constructor overloads we can create separation; further, adding a well-known location for the EasyPost.Request class to delegate the construction of the EasyPost.Client class, it opens up paths for managing multiple API Keys for cases where …
> Refactor client connection instantiation to support multiple API keys

- EasyPost/Rate.cs
This can be null when returned from the API in both Test and Production.
> Updated Delivery_date property

- EasyPost/Options.cs
Adding restricted_delivery was a mistake after discovering that the shipment option has already been implemented via undocumented delivery_confirmation values. Easypost's api docs were updated to reflect the full list of valid USPS delivery_confirmation shipment options.
> remove duplicate shipment option

- CHANGELOG.md
- README.md
Oddly enough, C# is the only CL to be missing a CHANGELOG. Added that with the last few changes as well as added missing Releasing info to the REAMDE.
> Added CHANGELOG and add releasing info to README

- README.md
Over the years, we've had many users write in confused by the `CreateAndBuy` example in our README. The code doesn't exist (maybe it did at one point?) I've provided an example of how to buy a batch (AKA "CreateAndBuy") without the need for us to actually add logic as this functionality is already supported via this library (see #134 for details).
This PR removes the bad `CreateAndBuy` example from the README.
Closes #134
> docs: removes CreateAndBuy example from README

- EasyPost.Net35/EasyPost.Net35.csproj
- EasyPost.Net40/EasyPost.Net40.csproj
- EasyPost.NetCore20/EasyPost.NetCore20.csproj
- EasyPost/EasyPost.csproj
We recently merged in a fix that adds the missing `VerificationDetails` object. This is in a new file. The PR was missing the compile targets to include it in the project. This simply adds the compile targets for the new file so when the project gets built, it's included.
> fix: adds missing VerificationDetails compile targets

- CHANGELOG.md
- EasyPost/Options.cs
Adds the missing `license_number` option. This is important for carriers such as Royal Mail.
> feat: adds missing license_number option

- EasyPost/Client.cs
This constructor is listed in the docs as though it should be publicly accessible.
> Add public access to Client delegate constructor

- CHANGELOG.md
Adds the following to the CHANGELOG from recent PR merges:
```
* Bumps `RestSharp` from `106.4.2` to `106.12.0`
* Changes the Client delegate constructor from `internal` to `public`
```
> docs: adds missing items to next release

- CHANGELOG.md
- EasyPost/Options.cs
fix: adds missing receiver_liquor_license option (required for FedEx alcohol shipments)
> fix: adds missing receiver_liquor_license option

- CHANGELOG.md
- EasyPost/Order.cs
- EasyPost/Shipment.cs
One call buys have been supported on the EasyPost platform for years by specifying the `carrier` and `service` to buy a rate for. The `service` key has simply been missing from the `Shipment` and `Order` objects for some time now with this client library. This should enable one-call-buys.
Real meat of the PR is `public string service { get; set; }`, the rest is auto-formatting.
Documentation: https://www.easypost.com/docs/api/csharp#shipments-one-call-buy-codesample
Closes #139
> feat: adds support for one-call-buys via the "service" key (closes #139)

- CHANGELOG.md
- EasyPost.Tests/BatchTest.cs
- EasyPost/Batch.cs
Removes the usused `orderBy` param from the Batch object.
> chore: remove unused orderBy param from Batch object

- EasyPost/Client.cs
This will include the current .NET framework that the user is running our library in in the User Agent made with every API call.
This isn't a perfect implementation, due to how Microsoft has changed how to get this information depending on the .NET framework, and it's difficult to implement a solution that can account (and work) regardless of the version the user is running (i.e. some classes needed to do the registry check for a version in newer .NET versions simply don't exist in older .NET versions, preventing the project from compiling). We can implement a more accurate solution in the future using interfaces, but for now, this will work as a first pass.
- If the .NET framework is v4.5 or higher (or lower than .NET Core 3.0 - we are dropping .NET Core 2.0 support anyway), it will only …
> Include .NET version in User Agent

- .github/workflows/ci.yml
- EasyPost.Tests/CarrierAccountTest.cs
- EasyPost.Tests/TrackerTest.cs
Improve the CI build by adding `-restore` in the `msbuild` step because `project.assets.json` could be not found after the NuGet restore
Ignore two unit tests that have multiple live API operations which can lead to timeout or unit test failed in the CI test, this issue will be resolved once we add VCR in the unit test.
> improve the CI build.

- CHANGELOG.md
- EasyPost.Net35/EasyPost.Net35.csproj
- EasyPost.Net40/EasyPost.Net40.csproj
- EasyPost.NetCore20/EasyPost.NetCore20.csproj
- EasyPost.NetCore31/EasyPost.NetCore31.csproj
- EasyPost.Tests/EventTest.cs
- EasyPost/EasyPost.csproj
- EasyPost/Event.cs
- EasyPost/EventCollection.cs
Finally, the C# library supports the ability to get all events with `Event.All()`
- The new `Event.All()` function to retrieve all events. Can optionally pass in a `Dictionary<string, object>` as parameter. Function returns an `EventCollection` object.
- Docstring for this function.
- Added new `EventCollection` class, which features:
- `public List<Event> events`
- `public bool has_more`
This is similar to how our other client libraries handle multiple events.
- A new `EventTest.TestRetrieveAll()` test for this feature
Classes, functions and tests have been imported/linked to all projects/versions, and all tests pass.
> Add support for retrieving all events

- CHANGELOG.md
- EasyPost.Net35/EasyPost.Net35.csproj
- EasyPost.Net40/EasyPost.Net40.csproj
- EasyPost.NetCore20/EasyPost.NetCore20.csproj
- EasyPost.NetCore31/EasyPost.NetCore31.csproj
- EasyPost.Tests/BatchTest.cs
- EasyPost/Batch.cs
- EasyPost/BatchCollection.cs
- EasyPost/EasyPost.csproj
Finally, the C# library supports the ability to get all batches with `Batch.All()`
- The new `Batch.All()` function to retrieve all batches. Can optionally ass in a `Dictionary<string, object>` as parameter. Function returns an `BatchCollection` object.
- Docstring for this function.
- Added new `BatchCollection` class, which features:
- `public List<Batch> batches`
- `public bool has_more`
This is similar to how our other client libraries handle multiple batches.
- A new `BatchTest.TestRetrieveAll()` test for this feature
Classes, functions and tests have been imported/linked to all projects/versions, and all tests pass.
Closes #95
> Add support for retrieving all batches

- EasyPost.Tests/ShipmentTest.cs
- EasyPost/Exception.cs
- EasyPost/Shipment.cs
Finally, the C# library supports the ability to re-rate a shipment with `shipment.RefreshRates()`
- The new `RefreshRates()` method to refresh the rates for a given shipment. Can optionally pass in a `Dictionary<string, object>` as parameter. Function replaces existing `rates` on shipment object, does not return anything.
- Docstring for this function.
- Added new `ResourceNotCreated` exception (extends standard `Exception`). This is used in the tests for this method (and can hopefully be used in the future). Thrown if the resource has not been created server-side.
- `RefreshRates()` throws `ResourceNotCreated` if the shipment object has not been created server-side (the shipment's `ID` is `null`)
- New `ShipmentTest.TestRerateShipment()` and …
> Add support for re-rating a shipment

- EasyPost/BatchCollection.cs
- EasyPost/EventCollection.cs
During our recent PR requests, we added a `BatchCollection` and `EventCollection` class, but forgot to have these new classes extend the `Resource` class.
All tests passed without it, but let's remain consistent with our class structure.
> Add missing class extension

- EasyPost.Net35/EasyPost.Net35.csproj
- EasyPost.Net40/EasyPost.Net40.csproj
- EasyPost.NetCore20/EasyPost.NetCore20.csproj
- EasyPost.NetCore31/EasyPost.NetCore31.csproj
- EasyPost.Tests.Net35/EasyPost.Tests.Net35.csproj
- EasyPost.Tests.Net40/EasyPost.Tests.Net40.csproj
- EasyPost.Tests.NetCore31/EasyPost.Tests.NetCore31.csproj
- EasyPost.Tests/EasyPost.Tests.csproj
- EasyPost.Tests/InsuranceTest.cs
- EasyPost/EasyPost.csproj
- EasyPost/Insurance.cs
- EasyPost/InsuranceCollection.cs
- EasyPost/Tracker.cs
Finally, our C# library supports Insurance!
- A new `Insurance` class, with `Create()`, `Retrieve()`, `Refresh()` and `All()` functions
- A new `InsuranceCollection` class required for the `Insurance.All()` function
- Tests for all functionalities
> Add support for Insurance objects

- CHANGELOG.md
- EasyPost.Net/User.cs
- EasyPost.NetFramework/User.cs
- EasyPost.Tests.Net/UserTest.cs
- EasyPost.Tests.NetFramework/UserTest.cs
C# library is currently missing the retrieve_me function. This is the same as retrieving a user without specifying an ID, but some libs have a specific function for this. Unifying this to make our libraries more consistent.
> Add RetrieveMe Convenience Functions.

- EasyPost/Client.cs
In `v2.8.1`, we introduced a functionality that retrieves the assembly version number of the EasyPost library being used, for inclusion in the User-Agent during API calls. This function, however, seems to be throwing an error on end-user systems, making the library effectively unusable.
After further research, it appears the initial implementation of collecting this information was incorrect. This PR:
- Introduces a new (better) way of getting the assembly information, following [Microsoft's own example](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblyname.version?view=netframework-4.8#examples) for .NET Framework 4.8 (the system used by the user that first reported the error; the solution is the same for all .NET/.NET Core/.NET Framework versions)
- Wraps this …
> Fix Assembly information retrieval

- CHANGELOG.md
- EasyPost.nuspec
- EasyPost/Client.cs
- EasyPost/VersionInfo.cs
Prepares v2.8.2 for release (begins diverging from the `master` branch, using `v2` branch.
> chore: prepare v2.8.2 for release

- EasyPost.Net/Refund.cs
- EasyPost.Net/RefundCollection.cs
- EasyPost.NetFramework/EasyPost.NetFramework.csproj
- EasyPost.NetFramework/Refund.cs
- EasyPost.NetFramework/RefundCollection.cs
- EasyPost.Tests.Net/RefundTest.cs
- EasyPost.Tests.Net/cassettes/refund/all.json
- EasyPost.Tests.Net/cassettes/refund/create.json
- EasyPost.Tests.Net/cassettes/refund/retrieve.json
- EasyPost.Tests.NetFramework/RefundTest.cs
Our C# client library is missing a `Refund` class. Let's fix that.
- A new `Refund` class, with `Create()`, `Retrieve()` and `All()` functions
- Refund tests for the .NET/.NET Core (VCR) and .NET Framework (live) versions in the respective test suites.
This branch is based on the `tests` branch, so please merge the `tests` branch first to avoid merge conflicts.
> Add missing Refund class

- CHANGELOG.md
- EasyPost.Net/Brand.cs
- EasyPost.Tests.Net/UserTest.cs
Our Brand class hasn't had a proper `id` property. This PR fixes that.
- Adds missing `id` for Brand class
- Adds test for checking Brand ID
> Add missing ID property to Brand class

- EasyPost.Net/CarrierAccount.cs
- EasyPost.Net/User.cs
- EasyPost.Net/Webhook.cs
- EasyPost.NetFramework/CarrierAccount.cs
- EasyPost.NetFramework/User.cs
- EasyPost.NetFramework/Webhook.cs
- EasyPost.Tests.Net/CarrierAccountTest.cs
- EasyPost.Tests.Net/UserTest.cs
- EasyPost.Tests.Net/WebhookTest.cs
- EasyPost.Tests.NetFramework/CarrierAccountTest.cs
- EasyPost.Tests.NetFramework/UserTest.cs
- EasyPost.Tests.NetFramework/WebhookTest.cs
Our functions to delete a `User`, `CarrierAccount` or `Webhook` are called `Destroy()`. This could get confused with the programmatic concept of destroying a local object vs. deleting a server-side element. Renaming them to `Delete()` makes it more clear what these functions do.
This PR:
- Renames `Destroy` functions to `Delete`
> Rename `Destroy` functions to `Delete`

- EasyPost.Net/Batch.cs
- EasyPost.NetFramework/Batch.cs
- EasyPost.Tests.Net/BatchTest.cs
- EasyPost.Tests.Net/cassettes/batch/create_and_buy.json
- EasyPost.Tests.NetFramework/BatchTest.cs
Our C# library is missing the CreateAndBuy one-step function for batches that is present in other client libraries.
This PR:
- Adds `CreateAndBuy` function to `Batch`
- Adds unit tests and required VCR cassettes
> Add CreateAndBuy function to Batch class

- .github/workflows/ci.yml
- EasyPost.Net/Address.cs
- EasyPost.Net/Exception.cs
- EasyPost.Net/Order.cs
- EasyPost.Net/Pickup.cs
- EasyPost.Net/Shipment.cs
- EasyPost.NetFramework/Address.cs
- EasyPost.NetFramework/Exception.cs
- EasyPost.NetFramework/Order.cs
- EasyPost.NetFramework/Pickup.cs
- EasyPost.NetFramework/Shipment.cs
- EasyPost.Tests.FSharp/EasyPost.Tests.FSharp.fsproj
- EasyPost.Tests.FSharp/FSharpCompileTest.fs
- EasyPost.Tests.VB/EasyPost.Tests.VB.vbproj
- EasyPost.Tests.VB/VbCompileTest.vb
- EasyPost.sln
Per #151 , Visual Basic cannot tell the difference between a static and non-static version of the same method signature. This is an issue because we have both static and non-static `Create` methods in a handful of our classes.
The non-static methods, however, are for creating/recreating an object in case its `id` is blank, which logically does not make much sense. Why are we checking, i.e. when calling `myOrder.Buy()` whether `myOrder` exists? Of course it does.
The methods were likely implemented for a single-altered structure, accounting for if the `id` was somehow blank/not returned by the API. There are better ways to handle this. For now, I have removed the `id` check, but if it is truly necessary, we should have an exception thrown, rather have the library attempt to regenerate the …
> WIP: Removing non-static `Create` methods

- CHANGELOG.md
- EasyPost.Tests.NetStandard20/EasyPost.Tests.NetStandard20.csproj
- EasyPost.Tests/ReportTest.cs
- EasyPost.Tests/VCR.cs
- EasyPost.Tests/cassettes/report/all.json
- EasyPost.Tests/cassettes/report/create_payment_log_report.json
- EasyPost.Tests/cassettes/report/create_report_with_additional_columns.json
- EasyPost.Tests/cassettes/report/create_report_with_columns.json
- EasyPost.Tests/cassettes/report/create_shipment_invoice_report.json
- EasyPost.Tests/cassettes/report/create_shipment_report.json
- EasyPost.Tests/cassettes/report/create_tracker_report.json
- EasyPost.Tests/cassettes/report/retrieve_payment_log_report.json
- EasyPost.Tests/cassettes/report/retrieve_refund_report.json
- EasyPost.Tests/cassettes/report/retrieve_shipment_invoice_report.json
- EasyPost.Tests/cassettes/report/retrieve_shipment_report.json
- EasyPost.Tests/cassettes/report/retrieve_tracker_report.json
- EasyPost.nuspec
- EasyPost/Properties/VersionInfo.cs
- EasyPost/Report.cs
- EasyPost/VersionInfo.cs
Our API now supports specifying `columns` and `additional_columns` when [creating reports](https://www.easypost.com/docs/api#create-a-report).
This PR:
- Adds support for specifying `columns` and `additional_columns` (both lists of strings) in the `parameters` dictionary passed into `Report.Create(parameters)`
- Adds unit tests for this feature
Unfortunately, since the API response does not indicate the columns used for a report, the only way to ensure the report actually includes the columns requested would be to make a live API call, download the generated CSV report and parse its column headers. That is a complex unit test with many points of failure and prevents us from using VCR.
Instead, we simply assume that if no error is thrown during the API call to generate and retrieve the …
> [feat] Support for `columns` and `additional_columns` on Report creation

- EasyPost.Tests/AddressTest.cs
- EasyPost.Tests/BatchTest.cs
- EasyPost.Tests/CarrierAccountTest.cs
- EasyPost.Tests/CustomsInfoTest.cs
- EasyPost.Tests/CustomsItemTest.cs
- EasyPost.Tests/EventTest.cs
- EasyPost.Tests/InsuranceTest.cs
- EasyPost.Tests/OrderTest.cs
- EasyPost.Tests/ParcelTest.cs
- EasyPost.Tests/PickupTest.cs
- EasyPost.Tests/RateTest.cs
- EasyPost.Tests/RefundTest.cs
- EasyPost.Tests/ScanFormTest.cs
- EasyPost.Tests/ShipmentTest.cs
- EasyPost.Tests/TrackerTest.cs
- EasyPost.Tests/WebhookTest.cs
- EasyPost/IResource.cs
- EasyPost/Resource.cs
For a number of our unit tests, we're simply comparing the IDs of the original and test object, rather than comparing the whole objects. This PR introduces that functionality.
- New overloaded function for evaluating equality of Resource objects
- New function to convert Resource objects to JSON representation
- Unit tests now assert whole-object equality rather than just IDs (sans special cases where the two objects have known differences; ID comparison only in those situations)
> Compare objects rather than IDs in unit tests

- CHANGELOG.md
- EasyPost/CustomsInfo.cs
Customs Info class is currently missing the `declaration` attribute.
This PR adds the `declaration` attribute in the Customs Info class.
> add declaration attribute in customs info class.

- EasyPost/Message.cs
- EasyPost/Pickup.cs
Our C# library was expecting messages in pickups to be a list of strings, rather than a list of objects (a la [Go](https://github.com/EasyPost/easypost-go/blob/a786f1ea7500fe117613b80851d8caa93b5554d5/pickup.go#L37) and [Java](https://github.com/EasyPost/easypost-java/blob/b24b4f0972666537d0e642438fd0d2e2817be420/src/main/java/com/easypost/model/Pickup.java#L20)), so the JSON deserialization was failing if any messages were included as part of the response to a pickup creation.
- `messages` in `Pickup` class now expects a list of `Message` rather than a list of strings
- `Message` class now has `carrier_account_id` attribute
Tested with bad cassettes (incorrect pickup dates to trigger a message from USPS), deserialization worked …
> Fix Pickup messages deserialization

- CHANGELOG.md
- UPGRADE_GUIDE.md
Let's clarify what [removing the non-static `Create()` functions](https://github.com/EasyPost/easypost-csharp/pull/230) means for users, and what migrations are needed to account for this change.
N/A
> Clarify upgrade guide

- CHANGELOG.md
- EasyPost.Tests/TestUtils.cs
- EasyPost/Client.cs
- EasyPost/Utilities/RuntimeInfo.cs
- Capture OS details in User-Agent
- Removed outdated, unused X-Client-User-Agent header
- Improve user agent detail calculation logic
- Implementation works on all supported versions of .NET. Examples below (notice the different `.NET` value):
- All tests pass as expected
- The legacy .NET Framework does not have pretty version numbers (will look something like 4.0.xxxx.xxxx), but it thankfully sticks out compared to the other .NET/.NET Core versions (which follow the X.Y.Z pattern)
- In the screenshots above, the `OSVersion` for .NET 5 and .NET 6 report "12.0.1", while .NET Core 3.1 and .NET Framework report "21.1.0.0". This is due to a change [introduced in .NET 5](https://docs.microsoft.com/en-us/dotnet/api/system.environment.osversion?view=net-6.0#remarks) that improved the accuracy …
> Capture OS details in User-Agent

- .github/workflows/ci.yml
- EasyPost.Tests.FSharp/EasyPost.Tests.FSharp.fsproj
- EasyPost.Tests.VB/EasyPost.Tests.VB.vbproj
- EasyPost.Tests/EasyPost.Tests.csproj
- EasyPost/Base/Address.cs
- EasyPost/EasyPost.csproj
- EasyPost/Exception.cs
- EasyPost/Pickup.cs
- EasyPost/Shipment.cs
- Makefile
- Add [SecurityCodeScan](https://security-code-scan.github.io/#Installation) as NuGet dependency (during build, not install)
- Add SecurityCodeScan as CI step
- Fix some linting
- Performed code analysis in IDE (NuGet package would step in, no errors found)
- Tested build process (NuGet package would step in, no errors found)
- Ran code manually through standalone scanner (no errors found)
- All unit tests pass as expected, no new recordings needed
- We should enable proper [Code Scanning via GitHub](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning). SecurityCodeScan can [take advantage](https://github.com/marketplace/actions/securitycodescan) of that feature (see comment in `ci.yml`)
> Add static analysis tool

- Makefile
- scripts/publish_all_nuget.bat
- scripts/publish_nuget.bat
- scripts/setup.bat
Let's make it as easy as possible for someone with a "fresh" Windows machine to get their environment up and running for developing and testing our code.
- New script/Makefile step "setup" installs all required .NET versions and third-party tools (NuGet CLI tool for a variety of functions, SnInstallPfx for signing DLLs)
(Bit of a catch-22 here, as the user WILL still need to install Make (and, perhaps in the process, Chocolatey) to be able to use our Makefile. They could always bypass the Makefile shortcut and simply call the `setup.bat` script directly via a terminal. The `setup.bat` script does NOT install Chocolatey or Make.
> Automate the environment setup process

- CHANGELOG.md
- EasyPost.Tests/ShipmentTest.cs
- EasyPost/Shipment.cs
- generate_test_reports.sh
- Users can optionally provide an EndShipper ID when buying a shipment
- Unit test for feature won't work without serious dependency injection and mocking
- Can manually confirm that the parameter was passed properly in the API call
> feat: Include optional EndShipper ID when buying a shipment

- EasyPost/Options.cs
LaserShipV2 extra required parameters added to the Options.cs class
Extra three required parameter added for LaserShipV2 carrier.
The below documentation explains the why these parameters needed and test conditions and results.
https://support.easypost.com/hc/en-us/articles/360062036932-Lasership-V2-Guide
> LaserShipV2 extra required parameters // umitguner

- EasyPost/Models/API/Options.cs
- Port of https://github.com/EasyPost/easypost-csharp/pull/334
- N/A
- Something we missed in the original PR is that DropoffMaxDatetime is a string, while PickupMaxDatetime is a DateTime object. Here, both are made DateTime objects for convenience (minor breaking change)
> Add LaserShipV2 datetime parameters

- EasyPost/Services/PartnerService.cs
- Fix a nullability warning for CreateStripeToken function in .NET 5.0 due to nullability of form-encoded parameters (specific to .NET 5.0, see below):
- All unit tests pass
- No modification to cassettes needed
> Fix nullability warning for CreateStripeToken function in .NET 5.0

- Makefile
- scripts/setup.sh
- Use Microsoft's [hosted dotnet-install script](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install) to install required .NET SDKs on Unix via Makefile script
- Confirmed working on local machine
> - New script to setup .NET on Unix

- .github/workflows/ci.yml
- CHANGELOG.md
- EasyPost.Tests/ErrorTest.cs
- EasyPost/Exceptions/API/RedirectError.cs
- EasyPost/Exceptions/API/_Base.cs
- EasyPost/Exceptions/Constants.cs
- EasyPost/Utilities/Http.cs
- EasyPost/_base/EasyPostClient.cs
- Treat 1xx and 3xx status codes as errors
- All known 3xx status codes will throw a RedirectError exception
- Unknown 3xx status codes will throw a UnexpectedHttpError exception (same as 5xx)
- Any 1xx status code (known or unknown) will throw a UnexpectedHttpError exception
- Add 3xx to HTTP error parsing unit test
- New unit test for testing unexpected 3xx status code
> fix: raise errors for non-2xx status codes

- EasyPost.Tests/EasyPost.Tests.csproj
- EasyPost.Tests/TestUtils.cs
- EasyPost.Tests/packages.lock.json
- Expire unit test cassettes older than 6 months (throws a warning)
- Note: Includes a new dependency that is missing in EasyVCR. Will drop from requirements once EasyVCR is fixed
- All unit tests pass
> Expire unit test cassettes after 6 months

- CHANGELOG.md
- EasyPost.Tests/ServicesTests/PartnerServiceTest.cs
- EasyPost.Tests/TestUtils.cs
- EasyPost.Tests/_Utilities/UnitTest.cs
- EasyPost/Services/PartnerService.cs
- Fix bug where the temporary API key switch while adding a referral credit card did not switch back after request completed
- Add unit test to verify API key switching is correct
- Add Mock key to TestUtils
> Fix API key bug when adding credit card to referral user

- EasyPost.Tests/ServicesTests/PartnerServiceTest.cs
- EasyPost/Services/PartnerService.cs
- Handle switching the API key back (https://github.com/EasyPost/easypost-csharp/pull/361) even on exception
- New unit test to confirm that API key is reverted even when API call fails
> Improve logic handling API key switch on exception

- .github/workflows/ci.yml
- EasyPost.Tests/EasyPost.Tests.csproj
- EasyPost.Tests/packages.lock.json
- Makefile
- check_coverage.sh
- generate_test_reports.sh
- New Makefile step to check code coverage (via Bash script)
- New CI step to check code coverage on every push
- Enforce 90% line coverage for unit tests (via `coverage_check.sh`)
- Tested locally, confirmed Makefile step/script is working as expected
- Tested with high threshold, failure as expected
- Tested with low threshold, success as expected
- Example: https://github.com/EasyPost/easypost-csharp/actions/runs/3415290082/jobs/5684249174
> Enforce code coverage threshold

- .github/workflows/ci.yml
- EasyPost.Tests/EasyPost.Tests.csproj
- EasyPost.Tests/packages.lock.json
- EasyPost.nuspec
- EasyPost/EasyPost.csproj
- EasyPost/packages.lock.json
- check_coverage.sh
- Add net7.0 support to source and unit tests
- Use net7.0 when testing F# and VB compatibility
- Add net7.0 support to nuspec
- Tested locally using .NET 7 RC, works as expected
- GitHub CI will test .NET 7 as well
-~~In draft mode until GitHub Actions runners add .NET 7 support: https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#net-core-sdk, https://github.com/actions/runner-images/issues/6539~~ Resolved by forcibly installing .NET versions via [`actions/setup-dotnet`](https://github.com/actions/setup-dotnet) rather than relying on pre-installed .NET on GitHub runner
- This will help us lock down any .NET version issues.
> Project, test suite, NuGet package updated to add .NET 7 support

- Makefile
- scripts/build_release_nuget.bat
- scripts/dependencies.txt
- scripts/install_cert.bat
- scripts/sign_dlls.bat
- scripts/sign_nuget.bat
Confusion over the renewed code signing certificate caused a premature change to the code signing/NuGet packing process. Most of those changes have been reverted in this PR, and the process will largely stay the same as it was.
- N/A
> Undo code signing changes

- .github/workflows/ci.yml
Anything older than Node 16 on CI is deprecated. Bumping actions used to become compliant.
> fix: bump CI actions to upgrade to Node 16

- EasyPost.Tests.FSharp/packages.lock.json
- EasyPost.Tests/ServicesTests/AddressServiceTest.cs
- EasyPost.Tests/ServicesTests/BatchServiceTest.cs
- EasyPost.Tests/ServicesTests/EndShipperServiceTest.cs
- EasyPost.Tests/ServicesTests/EventServiceTest.cs
- EasyPost.Tests/ServicesTests/InsuranceServiceTest.cs
- EasyPost.Tests/ServicesTests/PartnerServiceTest.cs
- EasyPost.Tests/ServicesTests/PickupServiceTest.cs
- EasyPost.Tests/ServicesTests/RefundServiceTest.cs
- EasyPost.Tests/ServicesTests/ReportServiceTest.cs
- EasyPost.Tests/ServicesTests/ScanFormServiceTest.cs
- EasyPost.Tests/ServicesTests/ShipmentServiceTest.cs
- EasyPost.Tests/ServicesTests/TrackerServiceTest.cs
- Remove the assertion that `HasMore` for all collection types is "true", since we can't guarantee that the API will always return "true" for the "has_more" key (that a collection has more than one page of results)
- Unit tests updated, no re-recording needed
> Remove inconsistent `HasMore` assertion from unit tests

- EasyPost/Services/PickupService.cs
- EasyPost/Services/ReportService.cs
- EasyPost/Services/ScanFormService.cs
- EasyPost/Services/ShipmentService.cs
- EasyPost/Services/TrackerService.cs
This PR removes an inconsistent anti-pattern of storing a copy of the Client used to retrieve an XCollection inside the collection itself.
This was implemented earlier to cater to the initial concept of instance-based functions in the library. While that pattern still exists (for now), this was applied inconsistently. It's not a bug, but we should remove it to avoid unintended consequences.
Upcoming work for getting the next page of a paginated collection will most likely reintroduce this, but holistically.
This is unlikely to introduce a breaking change for end-users (unless they were stepping outside of expected workflow patterns)
- No changes to unit tests or functionality
> [chore] Fix bad anti-pattern

- EasyPost.Tests/ServicesTests/AddressServiceTest.cs
- EasyPost.Tests/ServicesTests/EndShipperServiceTest.cs
- EasyPost.Tests/ServicesTests/ServiceTest.cs
- EasyPost.Tests/cassettes/net/address_service/get_next_page.json
- EasyPost.Tests/cassettes/net/base_service/get_next_page.json
- EasyPost.Tests/cassettes/net/base_service/get_next_page_size_limit.json
- EasyPost.Tests/cassettes/net/end_shipper_service/get_next_page.json
- EasyPost.Tests/cassettes/netstandard/base_service/get_next_page.json
- EasyPost.Tests/cassettes/netstandard/base_service/get_next_page_size_limit.json
- EasyPost/Exceptions/General/EndOfPaginationError.cs
- EasyPost/Models/API/Address.cs
- EasyPost/Models/API/ApiKey.cs
- EasyPost/Models/API/Batch.cs
- EasyPost/Models/API/EndShipper.cs
- EasyPost/Models/API/Event.cs
- EasyPost/Models/API/Insurance.cs
- EasyPost/Models/API/Pickup.cs
- EasyPost/Models/API/ReferralCustomer.cs
- EasyPost/Models/API/Refund.cs
- EasyPost/Models/API/Report.cs
- EasyPost/Models/API/ScanForm.cs
- EasyPost/Models/API/Shipment.cs
- EasyPost/Models/API/Tracker.cs
- EasyPost/Models/Shared/Collection.cs
- EasyPost/Services/AddressService.cs
- EasyPost/Services/EndShipperService.cs
- Makefile
This is a proof-of-concept for a new `GetNextPage` function for each of our services (e.g. `Address`) (as needed).
Users pass in the current paginated collection object (e.g. `AddressCollection`), and it will craft the parameters and execute the request to retrieve the next page of results for a paginated collection (or throw an exception if there are no more pages to retrieve).
The underlying base functions for handling this utilize interfaces to abstract away the type restrictions. This means that the base functions will handle any type of paginated collection thrown at them, with the upstream function being more specific and locked down to a specific type (ex. you can't pass a `ShipmentCollection` object into the `Address.GetNextPage()` function).
The base function to calculate …
> [feat] POC: Functionality to get the next page of a paginated collection

- EasyPost.Tests/ExceptionsTests/ExceptionsTest.cs
- EasyPost.Tests/packages.lock.json
- EasyPost/Exceptions/API/_Base.cs
- EasyPost/Models/API/Error.cs
Most of the time, the `message` property of an `Error` object's JSON data is a string, but occasionally, our API sends something other than a string.
For example:
"message" is a JSON array
```
{
"error": {
...
"message": [
"ERROR 1",
"ERROR 2"
], 
...
}
```
"message" is a JSON dictionary
```
{
"error": {
...
"message": {
"errors": [
"ERROR 1",
"ERROR 2"
]
},
...
}
```
This PR enhances the JSON deserialization process for `Error` objects to account for the "message" being an array, being a JSON dictionary, or being empty.
- Unit tests updated to confirm logic works as expected
> Handle any potential type of "message" in an Error 

- CHANGELOG.md
- EasyPost.Tests/ExceptionsTests/ExceptionsTest.cs
- EasyPost/Constants.cs
- EasyPost/Exceptions/API/_Base.cs
Better handling for API timeout errors. Rather than proceeding with error handling, which produces a `ConnectionError` exception with an ambiguous error message, an API timeout will instead produce a `TimeoutError` with an understandable error message.
Portion of #433 
- New unit test to confirm functionality
> Better error message for API timeouts

- EasyPost.Tests/BetaFeaturesTests/ServicesTests/BillingServiceTest.cs
- EasyPost.Tests/ServicesTests/BillingServiceTest.cs
- EasyPost.Tests/ServicesTests/PartnerServiceTest.cs
- EasyPost.Tests/ServicesTests/ServiceTest.cs
- EasyPost.Tests/TestUtils.cs
- EasyPost/Http/Method.cs
- EasyPost/Http/Request.cs
- EasyPost/Models/API/Address.cs
- EasyPost/Models/API/Batch.cs
- EasyPost/Models/API/CarrierAccount.cs
- EasyPost/Models/API/EndShipper.cs
- EasyPost/Models/API/Insurance.cs
- EasyPost/Models/API/Order.cs
- EasyPost/Models/API/Pickup.cs
- EasyPost/Models/API/Shipment.cs
- EasyPost/Models/API/User.cs
- EasyPost/Models/API/Webhook.cs
- EasyPost/Services/Beta/ReferralService.cs
- EasyPost/Services/PartnerService.cs
- EasyPost/_base/EasyPostClient.cs
- EasyPost/_base/EasyPostObject.cs
- EasyPost/_base/WithClient.cs
In preparing to drop RestSharp as a dependency, this introduces a custom drop-in replacement for RestSharp HTTP method enums, built currently as a bridge to be finished later when RestSharp is officially dropped. The custom implementation is required, as PATCH does not exist in .NET Standard 2.0 and must be manually supplemented.
All functions that accept RestSharp HTTP method enums have been updated to accept the new custom methods, and internal logic has been updated to account for the change. No user-facing changes have been introduced.
Part of #433 
- All tests pass
- Testing utilities (mocking) have been updated to account for the new methods
> [chore] Replace HTTP method, prep for RestSharp drop

- EasyPost.Tests.FSharp/packages.lock.json
- EasyPost.Tests.VB/packages.lock.json
- EasyPost.Tests/BetaFeaturesTests/ServicesTests/BillingServiceTest.cs
- EasyPost.Tests/ClientTest.cs
- EasyPost.Tests/EasyPost.Tests.csproj
- EasyPost.Tests/ExceptionsTests/ExceptionsTest.cs
- EasyPost.Tests/HttpTests/ClientConfigurationTest.cs
- EasyPost.Tests/ServicesTests/BillingServiceTest.cs
- EasyPost.Tests/ServicesTests/PartnerServiceTest.cs
- EasyPost.Tests/ServicesTests/ServiceTest.cs
- EasyPost.Tests/TestUtils.cs
- EasyPost.Tests/UtilitiesTests/HttpTest.cs
- EasyPost.Tests/packages.lock.json
- EasyPost/BetaClient.cs
- EasyPost/Client.cs
- EasyPost/EasyPost.csproj
- EasyPost/Exceptions/API/_Base.cs
- EasyPost/Http/ClientConfiguration.cs
- EasyPost/Http/Method.cs
- EasyPost/Http/Request.cs
- EasyPost/Services/PartnerService.cs
- EasyPost/Utilities/Internal/Extensions/Http.cs
- EasyPost/Utilities/Internal/JsonSerialization.cs
- EasyPost/_base/EasyPostClient.cs
- EasyPost/packages.lock.json
Removes all usage of RestSharp and drops the package as a dependency.
This library was using RestSharp as an HTTP client, but was not utilizing the package's JSON deserialization capabilities after [a custom de/serializer was implemented last year](https://github.com/EasyPost/easypost-csharp/commit/d06961811ae613fd0d69808fae4e65ac1e143df9). Rather than continuing to include this package under-utilized, the library has been restructured internally to simply use the default `HttpClient` built into the .NET framework and drop an unnecessary dependency.
Due to the immutability of connection timeouts (once the timeout length for an HttpClient has been set, it cannot be changed), connection timeout must be set during the construction of the `EasyPostClient` (and subsequent Beta client). This PR …
> Remove RestSharp usage

- EasyPost/BetaClient.cs
- EasyPost/Client.cs
- EasyPost/ClientConfiguration.cs
- EasyPost/Http/Request.cs
- EasyPost/_base/EasyPostClient.cs
- EasyPost/_base/EasyPostService.cs
- EasyPost/packages.lock.json
- Makefile
This PR implements the IDisposable interface to a number of in-memory objects to improve memory management and avoid orphaned objects.
The garbage collector in .NET will likely catch the majority of these objects without explicit dispose instructions, but this guarantees that no-longer-referenced objects are in fact destroyed.
Specifically:
- After every HTTP request is made, the `Request` object is no longer needed, and so is explicitly destroyed once that process is finished.
- When an `EasyPostClient` that a user would create is no longer needed (perhaps it was a one-off instance to use a specific API key), this will ensure that the `ClientConfiguration` and all `EasyPostService`s associated with that client are also destroyed.
- N/A
Please select the option(s) that are relevant to …
> [chore] Explicit IDisposable implementations for better memory management

- EasyPost/Services/AddressService.cs
- EasyPost/Services/ApiKeyService.cs
- EasyPost/Services/BatchService.cs
- EasyPost/Services/Beta/CarrierMetadataService.cs
- EasyPost/Services/Beta/RateService.cs
- EasyPost/Services/Beta/ReferralCustomerService.cs
- EasyPost/Services/BillingService.cs
- EasyPost/Services/CarrierAccountService.cs
- EasyPost/Services/CarrierTypeService.cs
- EasyPost/Services/CustomsInfoService.cs
- EasyPost/Services/CustomsItemService.cs
- EasyPost/Services/EndShipperService.cs
- EasyPost/Services/EventService.cs
- EasyPost/Services/InsuranceService.cs
- EasyPost/Services/OrderService.cs
- EasyPost/Services/ParcelService.cs
- EasyPost/Services/PickupService.cs
- EasyPost/Services/RateService.cs
- EasyPost/Services/ReferralCustomerService.cs
- EasyPost/Services/RefundService.cs
- EasyPost/Services/ReportService.cs
- EasyPost/Services/ScanFormService.cs
- EasyPost/Services/ShipmentService.cs
- EasyPost/Services/TrackerService.cs
- EasyPost/Services/UserService.cs
- EasyPost/Services/WebhookService.cs
- EasyPost/_base/EasyPostClient.cs
- EasyPost/_base/EasyPostService.cs
- Rename Request functions to RequestAsync to fit best practice for async function naming:
- [Debated](https://github.com/dotnet/roslyn/issues/47592), but the [current convention](https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/task-asynchronous-programming-model#:~:text=The%20name%20of%20an%20async%20method%2C%20by%20convention%2C%20ends%20with%20an%20%22Async%22%20suffix.). Not user-facing or high-level, likely has no impact on actual code functionality.
- Stripe does it: https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Infrastructure/Public/StripeClient.cs#L105
- Add `ConfigureAwait(false)` to the functionality that executes the HTTP request, since this async function doesn't need to return to the same thread that spawned it once complete. …
> [chore] Best practices for async functions, avoid deadlocks (part 1)

- EasyPost.Tests/ServicesTests/WebhookServiceTest.cs
- EasyPost/Services/WebhookService.cs
Users can call `client.Webhook.Update` without a parameter set.
Also fix ordering of parameters in docstrings
- Unit test updated as needed
> [chore] Can update a Webhook without parameters

- EasyPost/Parameters/BaseParameters.cs
- EasyPost/Parameters/Beta/CarrierMetadata/Retrieve.cs
- EasyPost/Parameters/Shipment/GenerateForm.cs
- EasyPost/Parameters/Tracker/CreateList.cs
Follow-up to https://github.com/EasyPost/easypost-csharp/pull/468, the internal `.ToDictionary()` function needs to be public so end-users can override it as needed for custom Parameter sets.
- N/A
> [chore] Open parameter set .ToDictionary() function to downsteam mods

- EasyPost.Tests/TestUtils.cs
- EasyPost/_base/EasyPostClient.cs
Yet another method that was marked `internal` at the time, but should be `public` so end-users can more easily extend/mod our library as needed
- N/A
> [chore] Make ExecuteRequest publicly overridable by extended classes

- CHANGELOG.md
- EasyPost.nuspec
- EasyPost/Properties/VersionInfo.cs
> chore: prepare v5.3.0 for release

- EasyPost.Integration/Basics.cs
- EasyPost.Integration/Synchronous.cs
- EasyPost/_base/EasyPostObject.cs
- Make `Id` property of all EasyPostObject public (re #501 )
- Add integration test to verify users can set Id of an object
- Remove "Test" prefix from integration tests
> [fix] Make `Id` property of all EasyPostObject publicly settable

- EasyPost.Tests/ServicesTests/ShipmentServiceTest.cs
- EasyPost.Tests/ServicesTests/WithParameters/ShipmentServiceTest.cs
- EasyPost/Models/API/RateWithEstimatedDeliveryDate.cs
- Fixes bad JSON mapping as reported in #505 
- Sets type to `DateTime` rather than string to match `PlannedShipDate`
- Tests updated to check for value of time-in-transit data to verify valid JSON deserialization
- All tests pass, no re-recording needed.
> [bug] Fix bad JSON property for estimated delivery date

- EasyPost.Tests/ExceptionsTests/ExceptionsTest.cs
- EasyPost.Tests/Fixture.cs
- EasyPost.Tests/ParametersTests/ParametersTest.cs
- EasyPost.Tests/ServicesTests/WithParameters/CarrierAccountServiceTest.cs
- EasyPost.Tests/cassettes/net/carrier_account_service_with_parameters/create.json
- EasyPost.Tests/cassettes/net/carrier_account_service_with_parameters/create_with_custom_workflow.json
- EasyPost.Tests/cassettes/net/carrier_account_service_with_parameters/update.json
- EasyPost.Tests/cassettes/netstandard/carrier_account_service_with_parameters/create.json
- EasyPost.Tests/cassettes/netstandard/carrier_account_service_with_parameters/create_with_custom_workflow.json
- EasyPost.Tests/cassettes/netstandard/carrier_account_service_with_parameters/update.json
- EasyPost/Constants.cs
- EasyPost/Exceptions/General/InvalidParameterError.cs
- EasyPost/Parameters/CarrierAccount/CreateFedEx.cs
- EasyPost/Parameters/CarrierAccount/CreateUps.cs
- EasyPost/Services/CarrierAccountService.cs
Re: #365 
This PR introduces custom parameter sets for creating FedEx and UPS carrier accounts, as these two require different payload schemas than other carrier account types. These parameter sets (`CreateFedEx`, `CreateUps`) helps end-users know what parameters are required for these two specific carrier accounts compared to other carrier accounts, and handles elements such as parameter placement during serialization (standard for all parameter set objects) and auto-populating the carrier account type parameter.
These custom parameter sets can be used in the normal `Create` function. One step further, an exception will be raised if the user attempts to use the generic `Create` parameter set with, e.g. "FedExAccount" as its type (will force users to only use the `CreateFedEx` parameter …
> [feat] Add custom parameter sets for FedEx and UPS account creation

- EasyPost.Tests/ServicesTests/ServiceTest.cs
- EasyPost.Tests/cassettes/net/base_service/get_next_page.json
- EasyPost.Tests/cassettes/net/base_service/get_next_page_size_limit.json
- EasyPost.Tests/cassettes/netstandard/base_service/get_next_page.json
- EasyPost.Tests/cassettes/netstandard/base_service/get_next_page_size_limit.json
- EasyPost/Parameters/BaseParameters.cs
- EasyPost/Utilities/Internal/Extensions/Dictionaries.cs
RE: #512 
Removes an unneeded null check (from an earlier implementation of parameter sets) that was causing reused parameter sets for GetNextPage functionality to not be updated correctly.
- Add unit test to confirm GetNextPage parameter sets are getting updated properly behind-the-scenes by checking that multiple subsequent calls do in fact return different data.
> [fix] Fix parameter set serialization

- CHANGELOG.md
- EasyPost.Tests/ParametersTests/ParametersTest.cs
- EasyPost.nuspec
- EasyPost/Parameters/BaseParameters.cs
- EasyPost/Properties/VersionInfo.cs
- Prep changelog, version number for v5.6.0 release
- N/A
> Prep for v5.6.0 release

- EasyPost/Parameters/Shipment/Create.cs
- Add missing optional `return_address` and `buyer_address` parameters for Shipment creation parameter sets
> [fix] Add missing address parameters to Shipment create parameter set

- CHANGELOG.md
- EasyPost.nuspec
- EasyPost/Properties/VersionInfo.cs
> [chore] Prep release

- EasyPost.Tests/ParametersTests/ParametersTest.cs
- Adds a unit test walking through how overriding parameters in parameter sets (e.g. deprecating an existing parameter in favor of a new one, but both serialize to the same key in JSON) works
> [chore] Add unit test verifying how competing/overriding parameters work

- EasyPost.Integration/Extensions.cs
- EasyPost/Models/API/Address.cs
- EasyPost/Models/API/Batch.cs
- EasyPost/Models/API/EndShipper.cs
- EasyPost/Models/API/Event.cs
- EasyPost/Models/API/Insurance.cs
- EasyPost/Models/API/Pickup.cs
- EasyPost/Models/API/ReferralCustomer.cs
- EasyPost/Models/API/Refund.cs
- EasyPost/Models/API/Report.cs
- EasyPost/Models/API/ScanForm.cs
- EasyPost/Models/API/Shipment.cs
- EasyPost/Models/API/Tracker.cs
- EasyPost/Models/Shared/PaginatedCollection.cs
- EasyPost/_base/EasyPostClient.cs
We went a bit overboard during recent redesigns and refactors in terms of locking down our methods to internal-only, out of concern of preventing our end-users from accidentally shooting themselves in the foot.
However, bit by bit we've had to roll back changes to these for one reason or another. This PR opens up the three final remaining internal-only methods, allowing end-users to modify them or override them as they need in their own applications. This does NOT pose a vulnerability to our system.
- N/A
> [chore] Open internal methods

- CHANGELOG.md
- EasyPost/Parameters/Beta/Rate/Retrieve.cs
Users need to be able to define options when retrieving beta rates, same as for creating a shipment.
- N/A
> [fix] Add `Options` parameter for beta rate retrieval

- CHANGELOG.md
- EasyPost.Tests/ModelsTests/OptionsTests.cs
- EasyPost/Models/API/Options.cs
- EasyPost/Utilities/Internal/Extensions/Dictionaries.cs
- EasyPost/_base/EasyPostObject.cs
- Adds ability for users to provide additional option key-value pairs in case an option is not available in the library
- Add unit test to confirm that additional, user-defined options will be included in final serialized JSON payload
> [feat] Add ability to add custom options

- EasyPost.Tests/Fixture.cs
- EasyPost.Tests/ServicesTests/AddressServiceTest.cs
- EasyPost.Tests/ServicesTests/WithParameters/AddressServiceTest.cs
- EasyPost.Tests/cassettes/net/address_service/create_verify.json
- EasyPost.Tests/cassettes/net/address_service/create_verify_array.json
- EasyPost.Tests/cassettes/net/address_service/create_verify_strict.json
- EasyPost.Tests/cassettes/net/address_service/create_verify_strict_array.json
- EasyPost.Tests/cassettes/net/address_service_with_parameters/create_verify.json
- EasyPost.Tests/cassettes/net/address_service_with_parameters/create_verify_strict.json
- EasyPost.Tests/cassettes/netstandard/address_service/create_verify.json
- EasyPost.Tests/cassettes/netstandard/address_service/create_verify_array.json
- EasyPost.Tests/cassettes/netstandard/address_service/create_verify_strict.json
- EasyPost.Tests/cassettes/netstandard/address_service/create_verify_strict_array.json
- EasyPost.Tests/cassettes/netstandard/address_service_with_parameters/create_verify.json
- EasyPost.Tests/cassettes/netstandard/address_service_with_parameters/create_verify_strict.json
The unit test for testing the "verify" parameter on address creation was broken due to recent updates to downstream shipper systems that no longer considered the "incorrect" address we were sending to be incorrect.
To avoid having to find another "incorrect" address combination to trigger the original assertions, the unit test has been rewritten to send a guaranteed-incorrect address to the API, showcasing the difference in responses (the presence of delivery and/or zip4 verifications) based on whether the "verify" parameter was included.
This shifts the unit test away from having to account for server-side or downstream errors, and instead more closely tests what we're actually trying to test, that the "verify" parameter is being sent or not sent to the API, and that "verifications" are …
> [chore] Update create_verify unit test with better invalid address

- EasyPost/_base/EasyPostService.cs
The `EasyPostService` base class used for all services (e.g. `UserService`) was marked internal, meaning it could not be constructed or extended outside of the EasyPost module. This PR instead sets it to `protected`, meaning it can still not be constructed directly, but can be inherited. This can be helpful for end-users trying to make extensions or custom implementations of the services, allowing them to use the base service rather than having to re-implement all client HTTP functionality themselves.
- All unit tests pass
- Change does not affect compilation, run-time or linting
> [chore] Make base EasyPostService extendable outside module

- EasyPost.Tests/ModelsTests/OptionsTests.cs
- EasyPost/Exceptions/General/MissingPropertyError.cs
- EasyPost/Models/API/Options.cs
The `Options` object has always been in a weird middle-ground since we introduced parameter objects over a year ago, mainly because it it one of the few object classes in the library that is used in both requests (parameter sets) and responses (property of a `Shipment` model). Because the object is so large, with several dozen different "properties" (options), we've chosen not to duplicate it into request-specific and response-specific classes, but simply use the existing `Options` class, designed primarily for response JSON serialization, also for request JSON deserialization in parameter sets.
That has made the `Options` class difficult to transition to the parameter set construction paradigm we've established, especially because of how many properties it has that can be set.
This PR …
> [feat] Add ability to construct Options object from dictionary

- CHANGELOG.md
- EasyPost.Tests/baseTests/EasyPostObjectTests.cs
- EasyPost/_base/EasyPostObject.cs
- EasyPost/_base/EphemeralEasyPostObject.cs
- Override `ToString` for EasyPost objects to display object type and optional ID
> [chore] Display object type, ID when converting object to string

- CHANGELOG.md
- EasyPost.Integration/Basics.cs
- EasyPost/Parameters/CarrierAccount/CreateFedExSmartPost.cs
The constructor for `EasyPost.Parameters.CarrierAccount.CreateFedExSmartPost` was erroneously marked as internal and was not accessible to end-users. Because this is the only way users can create a FedEx Smartpost account using the Parameter objects in .NET, this was blocking some users from creating FedEx Smartpost accounts (without using the legacy raw dictionary approach).
- Add unit test to integration test to confirm that every constructor for every parameter set is publicly accessible.
> [fix] Make FedEx SmartPost parameter set accessible

- CHANGELOG.md
- EasyPost.Integration/Basics.cs
- EasyPost.Tests/ServicesTests/CarrierAccountServiceTest.cs
- EasyPost/Models/API/CarrierAccount.cs
- EasyPost/Models/API/CarrierFields.cs
This library was failing to deserialize a `CarrierAccount` from the API due to a failed deserialization of `CarrierFields`.
The previous assumption was that the API is returning "fields" in the JSON data for a `CarrierAccount` like so:
```json
{
"id": "ca_123",
"object": "CarrierAccount",
...
"fields": {
"credentials": [
{
"key": "account_number",
"visibility": "visible",
"label": "DHL Account Number",
"value": "123456"
},
{
"key": "country",
"visibility": "visible",
"label": "Account Country Code (2 Letter)",
"value": "US"
}
]
}
}
```
When in fact, the API is returning "fields" like so:
```json
{
"id": "ca_123",
"object": "CarrierAccount",
...
"fields": {
"credentials": {
"account_number": {
"visibility": "visible",
"label": "DHL Account Number",
"value": "123456"
},
"country": { …
```
> [fix] Invalid `CarrierFields` structure

- CHANGELOG.md
- EasyPost/Parameters/Order/Create.cs
- Add missing `BuyerAddress` and `ReturnAddress` parameters for `Order.Create` parameter set
- N/A
> [fix] Add missing parameters for creating orders

- EasyPost.nuspec
Following recommended best practices, as warned by our CI:
> WARNING: NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
> - Add lib or ref assemblies for the netcoreapp3.1 target framework
> WARNING: NU5130: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder have compatible matches, but not exact matches in the other location. Unless intentional, consult the list of actions below:
> - Add a dependency group for net8.0 to the nuspec
Removed unused 3.1 dependency group, added explicit 8.0 group
This does not impact users' ability to install and use our library, but does clear up inconsistencies and follows best …
> [chore] Clean up dependency groups in nuspec

- README.md
The `Parameters` section of the README still referenced them as being in beta and the incorrect syntax. This updates those to match what they are today.
> fix: docs about Parameters

- EasyPost.Tests/ClientTest.cs
- README.md
Added unit test showing that/how users can use a proxy by utilizing the custom `HttpClient` capabilities in this library. No changes to the source code are required for proxy support.
- Added unit tests for proxy configuration
> [chore] Demonstrate how users can provide their own proxy in custom HttpClient

- EasyPost/Parameters/CustomsItem/Create.cs
Add missing optional parameters (e.g. "code", "manufacturer", "eccn") to customs item parameter set.
Closes #567 
> [fix] Add missing parameters for customs item

- CHANGELOG.md
- EasyPost.nuspec
- EasyPost/Models/API/Batch.cs
- EasyPost/Properties/VersionInfo.cs
- Fix `Batch` class not inheriting `IBatchParameter`, preventing a `Batch` object from being used in a parameter set. Ex:
```csharp
Batch batch = await client.Batch.Retrieve("batch_123");
EasyPost.Parameters.Pickup.Create parameters = new()
{
Batch = batch, // compile error due to mismatch type
Instructions = "Special pickup instructions",
};
```
- Prep for v6.5.1 release
- Test snippet above now compiles
> [fix] Missing inheritance preventing `Batch` object use in parameter sets

- CHANGELOG.md
- EasyPost.nuspec
- EasyPost/Parameters/Pickup/Create.cs
- EasyPost/Properties/VersionInfo.cs
Either `Shipment` or `Batch` can be used when creating a Pickup, meaning the `Shipment` parameter should be optional, not required.
> [fix] Remove "required" validation for `Shipment` parameter of `Pickup.Create` set

- CHANGELOG.md
- EasyPost.Tests/ExceptionsTests/ExceptionsTest.cs
- EasyPost.Tests/ParametersTests/ParametersTest.cs
- EasyPost/Constants.cs
- EasyPost/Exceptions/General/InvalidParameterPairError.cs
- EasyPost/Parameters/BaseParameters.cs
- EasyPost/Parameters/Pickup/Create.cs
- EasyPost/Utilities/Internal/Attributes/RequestParameterAttribute.cs
- Makefile
In the `Pickup.Create` parameter set, both the `Shipment` and the `Batch` parameters are marked as "optional". In a vacuum, yes, neither is required on any given API call. However, at least one of them is required for every API call. With our current solution, since both are "optional", it is possible for an end-user to build a parameter set with both excluded, which will ultimately result in a bad request being sent to the API and a resultant error.
This PR introduces the concept of a dependency attribute/decorator which can denote the relationship between multiple parameters in a given parameter set. Specifically, the decorator denotes any other parameters that are dependent on the marked parameter, and what the condition is. For the `Shipment` and `Batch` example, both parameters are …
> [POC] Denote the interdependency between parameters in a parameter set

- CHANGELOG.md
- EasyPost.Tests/cassettes/net/user_service/get_next_page_of_children.json
- EasyPost.Tests/cassettes/netstandard/user_service/get_next_page_of_children.json
- EasyPost/Models/API/ChildUserCollection.cs
Pagination for listing child users needs to use "after_id", not "before_id"
> [bug] Fix pagination parameters for child user lists

- CHANGELOG.md
- EasyPost/Parameters/Address/Create.cs
Include `Verify` and `VerifyStrict` parameters for Address when creating as part of Shipment et. al creation request.
These were previously purposefully excluded when Address creation was being performed as part of a larger creation request, such as Shipment or Order, due to uncertainty about their placement in the payload schema. Consequently, this made for end-user confusion as to why address verification was not being performed as part of a Shipment or Order creation, and was causing Shipments and Orders to be successfully created with invalid Addresses.
> [fix] Include "verify" and "verify_strict" parameters for Address creation

- CHANGELOG.md
- EasyPost.Tests/ClientTest.cs
- EasyPost.Tests/HttpTests/ClientConfigurationTest.cs
- EasyPost.Tests/HttpTests/RequestTest.cs
- EasyPost.Tests/ServicesTests/ServiceTest.cs
- EasyPost.Tests/_Utilities/Assertions/AnyException.cs
- EasyPost.Tests/_Utilities/Assertions/CollectionAsserts.cs
- EasyPost.Tests/_Utilities/Assertions/DoesNotThrowAssert.cs
- EasyPost.Tests/_Utilities/Assertions/DoesNotThrowException.cs
- EasyPost.Tests/_Utilities/Assertions/GuardArgumentNotNull.cs
- EasyPost/Client.cs
- EasyPost/ClientConfiguration.cs
- EasyPost/Http/Request.cs
- EasyPost/_base/EasyPostClient.cs
- EasyPost/_base/EasyPostService.cs
Unhandled recursion during disposal of a `Client` or service would cause a stack overflow.
Closes #587
- Add unit tests to verify disposal does not cause stack overflow
> [fix] Recursion causing stack overflow when disposing client/service

- CHANGELOG.md
- EasyPost/Parameters/Tracker/All.cs
- Add `TrackingCodes` parameter for listing trackers
- Deprecated existing `TrackingCode` parameter
> [feat] Add TrackingCodes parameter

- CHANGELOG.md
- EasyPost.nuspec
- EasyPost/Properties/VersionInfo.cs
- Bump version to v6.8.0
- Update CHANGELOG
> [chore] Prep for v6.8.0 release

- EasyPost.Tests/HttpTests/RequestTest.cs
- EasyPost/Http/Request.cs
- EasyPost/Parameters/Tracker/All.cs
Using the new `tracking_codes` parameter for the `Tracker.All`parameter set was not serializing parameters properly, resulting in the value (a list of tracking codes) being lost in transit.
This PR introduces a fix in the query parameter construction process that will account for arrays. Specifically, the following list of tracking codes "001", "002", "003" will result in the following URL + query string being sent to the API: `https://api.easypost.com/v2/trackers?tracking_codes[]=001&tracking_codes[]=002&tracking_codes[]=003`. This is [the format expected by our backend](https://til.hashrocket.com/posts/syzssfozay-pass-array-of-values-as-query-string-in-rails-) for proper parsing.
Accomplishing this requires some string manipulation in the query building process, as this is not the …
> [fix] ]Handle serializing array/list parameters in GET/DELETE query strings

- EasyPost.Tests/Fixture.cs
- EasyPost.Tests/ParametersTests/ParametersTest.cs
- EasyPost/Models/API/ClaimPaymentMethod.cs
- EasyPost/Parameters/Claim/Create.cs
- EasyPost/Utilities/Cryptography.cs
- EasyPost/Utilities/Internal/Attributes/RequestParameterAttribute.cs
- EasyPost/Utilities/Internal/Enum.cs
- EasyPost/Utilities/Internal/Objects.cs
- Add missing `ACH` payment method type for claims
- Add missing `CheckDeliveryAddress` parameter for creating a claim
- Require `CheckDeliveryAddress` if `PaymentMethod` is `MailedCheck`
- Account for enums when enforcing interdependence of parameters*
*An unfortunate side effect of the custom enum classes used throughout the project, these cannot be passed into an attribute because they are not available at compile-time (unlike traditional enums). Instead, the attribute is provided the underlying primitive (string, float, int, etc.) value that is expected, and a pre-comparison check will convert any custom enum to its own underlying value, ensuring that the underlying primitive values are what is being compared in the interdependency check.
- Added unit test to confirm interdependency …
> [bug] Add missing claims parameters, fix interdependency parameter enforcement

- EasyPost.Integration/TestUtils.cs
- EasyPost.Tests/Fixture.cs
- EasyPost.Tests/ServicesTests/WebhookServiceTest.cs
- EasyPost.Tests/TestUtils.cs
- EasyPost/Parameters/Webhook/Create.cs
- EasyPost/Parameters/Webhook/Update.cs
- EasyPost/Services/WebhookService.cs
To the next dev that picks this up, we need to:
1. Add the `custom_headers` to the create and update parameter sets
2. Ensure that the update webhook overload function that uses the param sets doesn't need to have the params wrapped for it to work as expected
3. Update create/update webhook tests to pass in the `webhook_secret` and `custom_headers` to ensure we pass them correctly
> feat: add additional webhook params

- .github/workflows/ci.yml
We were using the default dotnet 8 for coverage uploading; however, we needed dotnet 9 for the tool to work. This should correct uploading coverage on CI.
Won't know till we land and check master CI output.
> fix: install proper dotnet version on CI for coverage

- CHANGELOG.md
- EasyPost.Tests/ServicesTests/CarrierAccountServiceTest.cs
- EasyPost.Tests/ServicesTests/WithParameters/CarrierAccountServiceTest.cs
- EasyPost.Tests/cassettes/net/carrier_account_service/create.json
- EasyPost.Tests/cassettes/net/carrier_account_service/create_with_oauth.json
- EasyPost.Tests/cassettes/net/carrier_account_service/update.json
- EasyPost.Tests/cassettes/net/carrier_account_service_with_parameters/create.json
- EasyPost.Tests/cassettes/net/carrier_account_service_with_parameters/create_ups.json
- EasyPost.Tests/cassettes/net/carrier_account_service_with_parameters/update.json
- EasyPost.Tests/cassettes/net/carrier_account_service_with_parameters/update_ups.json
- EasyPost.nuspec
- EasyPost/Constants.cs
- EasyPost/Parameters/CarrierAccount/CreateUps.cs
- EasyPost/Parameters/CarrierAccount/CreateUpsMailInnovations.cs
- EasyPost/Parameters/CarrierAccount/CreateUpsSurePost.cs
- EasyPost/Parameters/CarrierAccount/Update.cs
- EasyPost/Parameters/CarrierAccount/UpdateUps.cs
- EasyPost/Parameters/CarrierAccount/UpdateUpsMailInnovations.cs
- EasyPost/Parameters/CarrierAccount/UpdateUpsSurePost.cs
- EasyPost/Properties/VersionInfo.cs
- EasyPost/Services/CarrierAccountService.cs
> fix: endpoint used for ups create/update

- CHANGELOG.md
- EasyPost.nuspec
- EasyPost/Models/API/Claim.cs
- EasyPost/Models/API/ClaimPaymentMethod.cs
- EasyPost/Parameters/Claim/Create.cs
- EasyPost/Properties/VersionInfo.cs
> feat: adds reference to claims
